[tool.poetry]
name = "z-rad"
version = "24.9"
description = ""
authors = ["Radiomics Team of Radiation Oncology Department at University Hospital Zurich <zrad@usz.ch>"]
readme = "README.md"

packages = [
    { include = "zrad" }
]

[tool.poetry.dependencies]
python = "^3.12"
pydicom = "^3.0.0"
pyqt5 = "^5.15.11"
numpy = "^2.1.1"
pandas = "^2.2.2"
simpleitk = "^2.4.0"
scipy = "^1.14.1"
pywavelets = "^1.7.0"
openpyxl = "^3.1.5"
scikit-image = "^0.24.0"
scikit-learn = "^1.5.2"
opencv-python-headless = "^4.10.0.84"
joblib = "^1.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"